/* The public record — v4 (Matt, 2026-08-18): video cards are title + date/venue + topic + watch link; no spoken summaries — the tape is the record. Op-eds keep verbatim "What I wrote". */
window.RECORD = {
  sections: [
    { n: 'D', title: 'Water Rate Increase', sub: 'Water-rate accountability, and who pays for what · 3 appearances', cards: [
      { n: 17, head: 'Water Rate Increase Study Session',
        date: 'Apr 28, 2025', body: 'City Council Study Session',
        issue: 'A study session on raising water and sewer rates.',
        video: 'https://www.youtube.com/watch?v=GTrRJrOFoio&t=3424s' },
      { n: 18, head: 'Water Rate Increase Public Hearing, Part 1',
        date: 'Jul 14, 2025', body: 'City Council',
        issue: 'The first public hearing on the proposed water and sewer rate increase.',
        video: 'https://www.youtube.com/watch?v=DlL4texvusc&t=4962s' },
      { n: 19, head: 'Water Rate Increase Public Hearing, Part 2',
        date: 'Aug 11, 2025', body: 'City Council',
        issue: 'The second public hearing on the proposed water and sewer rate increase.',
        video: 'https://www.youtube.com/watch?v=gSA5B6AOCdI&t=4737s' }
    ]},
    { n: 'B', title: '13th Street Gas Station Convenience Store Expansion', sub: 'Housing, and the street I live on · 4 appearances', cards: [
      { n: 6, head: '13th Street Gas Station Expansion Hearing, Part 1',
        date: 'May 15, 2023', body: 'Planning Commission',
        issue: 'The gas station proposed expanding into the residential neighborhood by building a convenience store.',
        video: 'https://www.youtube.com/watch?v=6mov3f7YSMU&t=6143s' },
      { n: 7, head: '13th Street Gas Station Expansion Hearing, Part 2',
        date: 'Sep 05, 2023', body: 'Planning Commission',
        issue: 'The same project, back after the 90-day continuance.',
        video: 'https://www.youtube.com/watch?v=Ewrh2d4uORA&t=4281s' },
      { n: 8, head: '13th Street Gas Station Rezone Hearing',
        date: 'Oct 23, 2023', body: 'City Council',
        issue: 'Rezoning residential land on 13th Street to commercial so the gas station expansion could go forward.',
        video: 'https://www.youtube.com/watch?v=tNZtvxG13kA&t=7104s' },
      { n: 5, head: '13th Street Gas Station Runoff Concerns',
        date: 'Apr 08, 2024', body: 'City Council',
        issue: 'Raising my concerns with the council about runoff from the 13th Street gas station.',
        video: 'https://www.youtube.com/watch?v=FSwcOlx1A1M&t=683s',
        source: 'City Council minutes, Apr 08, 2024 · eight-exhibit photo package filed in the agenda packet ("Pooled Rainwater at 13th Street Gas Station," "Runoff Location, Note Sandbags Were Not Placed by Station," "Typical Example of Rainwater Contamination," and five more)' }
    ]},
    { n: 'C', title: 'Safe Streets', sub: 'Protecting what we built · 6 appearances', cards: [
      { n: 10, head: 'Pedestrian Safety on PCH',
        date: 'Feb 26, 2024', body: 'City Council',
        issue: 'Asking the city to pressure Caltrans to make PCH a safer street for pedestrians.',
        video: 'https://www.youtube.com/watch?v=z9SO0RYjzCM&t=565s',
        source: '"Matthew Terry Seal Beach Council Meeting" slide deck filed in the agenda packet, Feb 26, 2024' },
      { head: 'Pedestrian Safety on PCH',
        date: 'Mar 07, 2024', body: 'Sun News Op-Ed', oped: 'ed-pch', url: 'https://www.sunnews.org/guest-opinion-pedestrian-safety-at-intersections-along-pch/',
        issue: 'After my presentation to the council, the Sun News ran my piece making the same case in print.' },
      { n: 11, head: 'Safety Action Plan',
        date: 'Jan 13, 2025', body: 'City Council',
        issue: 'The city’s Safe Streets for All safety action plan.',
        video: 'https://www.youtube.com/watch?v=pzhO8SY46bQ&t=4061s',
        source: 'City Council minutes, Jan 13, 2025 · "Seal Beach Blvd. Safe Streets for All" existing-vs-proposed cross-section filed in the agenda packet' },
      { n: 12, head: 'Daylighting, Part 1',
        date: 'Mar 10, 2025', body: 'City Council',
        issue: 'How the city planned to carry out California’s daylighting law, which keeps parked cars back from the approach to a crosswalk so drivers can see people about to cross.',
        video: 'https://www.youtube.com/watch?v=4YsvRdfy0WU&t=1420s',
        source: 'City Council minutes, Mar 10, 2025 · responds to Item G, Feb 10, 2025 — cost-recovery amendment adding a daylighting non-compliance penalty' },
      { n: 13, head: 'PCH Bike Lane, Part 1',
        date: 'Mar 24, 2025', body: 'City Council',
        issue: 'Caltrans’ redesign of PCH through Seal Beach.',
        video: 'https://www.youtube.com/watch?v=gI5SZBWrDAg&t=2345s',
        source: 'City Council minutes, Mar 24, 2025 · written comment filed in the agenda packet · plans obtained from Caltrans by his own request for information' },
      { n: 14, head: 'Daylighting, Part 2',
        date: 'May 08, 2025', body: 'Capital Budget Workshop',
        issue: 'Asking the city to do more about the new daylighting law.',
        video: 'https://www.youtube.com/watch?v=xVSb3Atw8-8&t=3009s',
        source: 'City Council minutes, May 08, 2025, Special CIP Budget Workshop' },
      { n: 15, head: 'PCH Bike Lane, Part 2',
        date: 'Sep 22, 2025', body: 'City Council',
        issue: 'Cars parking in the new southbound bike lane on PCH near 5th Street.',
        video: 'https://www.youtube.com/watch?v=878GM9C4Tko&t=3960s',
        source: 'City Council minutes, Sep 22, 2025 · dated summary-of-events timeline filed in the agenda packet' }
    ]},
    { n: 'A', title: 'Main Street', sub: 'Four appearances, plus my time on the parking committee', cards: [
      { n: 1, head: 'Parklets Subcommittee Meeting',
        date: 'Oct 20, 2022', body: 'Parklets Subcommittee',
        issue: 'Whether Main Street should keep its parklets.',
        video: 'https://www.youtube.com/watch?v=iyNeLyNSxFE&t=1610s',
        source: 'Special Meeting — Parklets Subcommittee, Oct 20, 2022 (Seal Beach Council Chambers channel)' },
      { n: 2, head: 'Parklets on Main Street',
        date: 'Dec 12, 2022', body: 'City Council',
        issue: 'The staff report on the future of the Main Street parklets.',
        video: 'https://www.youtube.com/watch?v=j24RkgDK8W4&t=3089s',
        source: 'City Council minutes, Dec 12, 2022 (oral communications speaker list)' },
      { n: 3, head: 'Circuit Microtransit',
        date: 'Dec 11, 2023', body: 'City Council',
        issue: 'The council’s vote to fund the on-demand shuttle that became the Circuit.',
        video: 'https://www.youtube.com/watch?v=um27avoZ8Z4&t=3069s',
        source: 'City Council minutes, Dec 11, 2023 · Item F pulled from consent · Resolution 7467, accepting a $162,891 MSRC grant with a $162,892 local match for the Seal Beach Microtransit Service Pilot Program' },
      { n: 4, head: 'Sidewalk Dining on Main Street',
        date: 'Apr 15, 2024', body: 'Planning Commission',
        issue: 'A public hearing on the Main Street Specific Plan amendment for sidewalk dining.',
        video: 'https://www.youtube.com/watch?v=jxaa60P0dT4&t=1218s',
        source: 'Planning Commission minutes, Apr 15, 2024 (first name in the public-hearing speaker list)' }
    ]},
    { title: 'Citizen-Council Parking Advisory Ad Hoc Committee', cards: [
      { head: 'Citizen-Council Parking Advisory Ad Hoc Committee Proposal',
        date: 'Jun 12, 2023', body: 'City Council',
        issue: 'The council proposed creating a council-led ad hoc parking committee.',
        video: 'https://www.youtube.com/watch?v=yCd9f-iI6lA&t=2014s' },
      { head: 'Citizen-Council Parking Advisory Ad Hoc Committee Creation',
        date: 'Jun 26, 2023', body: 'City Council',
        issue: 'The council changed its proposal and created a citizen-led ad hoc parking committee.',
        video: 'https://www.youtube.com/watch?v=PaO4vKHLWvU&t=2769s' },
      { head: 'Citizen-Council Parking Advisory Ad Hoc Committee',
        date: 'Sep 2023 – Feb 2024', body: 'Committee',
        issue: 'The citizen-led parking committee looked into the possibility of implementing paid parking on Main Street.',
        meetings: [
          { d: 'Sep 13, 2023', t: 'First meeting', v: 'https://www.youtube.com/watch?v=1hf1A95iCKY' },
          { d: 'Sep 27, 2023', t: 'Refining the community parking survey', v: 'https://www.youtube.com/watch?v=WwXRCPWJc6U' },
          { d: 'Oct 12, 2023', t: 'Finalizing the survey and outreach plan', v: 'https://www.youtube.com/watch?v=Evg25FHjsfI' },
          { d: 'Nov 29, 2023', t: 'Reviewing the community survey results', v: 'https://www.youtube.com/watch?v=-qFwmTc5T5Y' },
          { d: 'Dec 04, 2023', t: 'First recommendations voted to council', v: 'https://www.youtube.com/watch?v=l7HDFMhpB_U' },
          { d: 'Feb 01, 2024', t: 'Final vote', v: 'https://www.youtube.com/watch?v=x--5KtX2Z4s' }
        ] },
      { head: 'Citizen-Council Parking Advisory Ad Hoc Committee Recommendation',
        date: 'May 28, 2024', body: 'City Council',
        issue: 'The parking committee’s recommendation was presented to the council.',
        video: 'https://www.youtube.com/watch?v=B_EdFHSkeUE&t=2898s' },
      { head: 'Paid Parking on Main Street',
        date: 'Jan 29, 2026', body: 'Sun News Op-Ed', oped: 'ed-parking', url: 'https://www.sunnews.org/debate-paid-parking-on-main-street/',
        issue: 'The Sun News ran a two-sided debate on Main Street parking. I wrote one side of it.' }
    ]},
    { title: 'Budget Workshops', sub: 'The argument I have been making longest', cards: [
      { n: 9, head: 'Budget Workshop',
        date: 'May 02, 2023', body: 'Capital Budget Workshop',
        issue: 'The capital budget workshop.',
        video: 'https://www.youtube.com/watch?v=-vhzrwoxn-c&t=59s',
        source: 'City Council minutes, May 02, 2023, Special Budget Workshop — CIP ("Speaker: Matthew Terry")' },
      { n: 16, head: 'Budget Study Session',
        date: 'Mar 24, 2025', body: 'City Council Study Session',
        issue: 'A public study session on the city budget.',
        video: 'https://www.youtube.com/watch?v=44tnWwYpeN4&t=4457s',
        source: 'City Council minutes, Mar 24, 2025, Special Budget Study Session (5:35 pm)' },
      { head: 'Five-Year Forecast Workshop',
        date: 'May 08, 2025', body: 'Capital Budget Workshop',
        issue: 'The city’s five-year financial forecast, and the revenue that funds it.',
        video: 'https://www.youtube.com/watch?v=xVSb3Atw8-8&t=6265s',
        source: 'City Council minutes, May 08, 2025, Special CIP Budget Workshop · second turn, made during the workshop discussion rather than the public-comment period — which is exactly why it is not in the minutes’ speaker list' }
    ]}
  ]
};
